language : java
jdk:
  -stage : Tests
  - openjdk8
  - openjdk13
before_install:
    - chmod +x src/test/java/com/example/helloworld
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - rm ~/.m2/settings.xml || true
    - ulimit -c unlimited -S
stages:
  - Construire
  - Tests
  - Deployer
jobs:
  include:
    - stage: Construire
      script: mvn package
      name: "Build"
    - script: mvn site
      name: "site"
    - stage: Tests
      image: maven:3-jdk-8
      script: mvn test
      name: "Integration Tests jdk8" 
    - stage: Tests
      image: maven:3-jdk-13
      script: mvn test
      name: "Integration Tests jdk13" 
    - stage: Deployer
      script: mvn deploy
      name: "Deploy"         
env:
  global:
      secure: "ComYGCV1mvuDcCc3GLEOj8vtN+AIL7Nvi8ofBRJHZm0RsS/QB/Jm3zCaLh6mNd/bZeGGyHaJ4EUhCWDP0nNnCsD/g6KFBdD02uuW21ClhY/li5r4cp3qDEBf3WR+zqGQfRZv4erkHrAkxpUwTIMpUIM85UTc9oOtceryjZIKttIwbMMl5PYiO3gPFp8QbU5xIZNOLKHQbY0hEvGGJnuXeLljaD1wgHXSl19DrAno6RV0/4Stouxtiz2KAIFoU3DRSxJcNy/BNAw5uq44hEnOpI6erfRidB0SXLOoref5zdul51/wPEE9+Bqs8TmhV/2YUjPdK74GOqWbsiJHuVAU23JDvf41nq8ogrlmwNWCMGocp756taZxSKjtMBjf+fVTaF7YGO9V1ufIJSQ46SC9UbJ7k7uXeCG1Z116zXQzgSY0ZxY9b46VxngItlPdOp6lPJGNzrwx5w/l8/Nr9GzS98yL1rT3pMFTt3CqNUNhCGyQQKLUkNWzeeI6plb5OAkec6xhzwOKbKTZ+lmK9H4al5YI/CU9ltelgNHxaEievm+3fw6JGzGS0gDY9jJYOXBGX69xecNZYFIYTNdUYDOnsnTivHl66zatHNjxQE9PQpNM5D6PhGz9eplAc7fIA3mGDrwnaGOgcpCUUr98xuQtnJC9X2AZNIo2/yY6d4QIcQs="
