language : java
jdk:
  - openjdk8
  - openjdk11
  - openjdk13

jobs:
  include:
    - stage: IntegrationTest
      script: ./src/test/java/com/example/helloworld/IntegrationTest.java
    - # stage name not required, will continue to use `test`
     # script: ./test 2
    - stage: deploy
      script: ./deploy
