language : java
jdk:
  - openjdk8
  - openjdk13
before_install:
    - chmod +x src/test/java/com/example/helloworld
    - chmod +x push.sh
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - rm ~/.m2/settings.xml || true
    - ulimit -c unlimited -S
    - git config --global user.email "mazeran.paul@gmail.com"
    - git config --global user.name "paulmazeranensg"
stages:
  - Construire
  - Test
  - Deployer
jobs:
  include:
    - stage: Construire
      name: "Build"
      script: mvn package
      script: mvn site
      after_success:
        - git checkout -b gh-pages
        - git add . 
        - git commit -m "documentation"
        - git remote add origin-pages https://token:16e8af4e6e6be2ad77858df775830e164527abbb@github.com/paulmazeranensg/TP_CI_CD_Mazeran.git > /dev/null 2>&1
        - git push --quiet --set-upstream origin-pages gh-pages
      name: "site"
    - stage: Test
      jdk: openjdk8
      script: mvn test
      name: "Integration Tests jdk8" 
    - stage: Test
      jdk: openjdk13
      script: mvn test
      name: "Integration Tests jdk13" 
    - stage: Deployer
      script: mvn deploy
      name: "Deploy"         
env:
  global:
      secure: "ComYGCV1mvuDcCc3GLEOj8vtN+AIL7Nvi8ofBRJHZm0RsS/QB/Jm3zCaLh6mNd/bZeGGyHaJ4EUhCWDP0nNnCsD/g6KFBdD02uuW21ClhY/li5r4cp3qDEBf3WR+zqGQfRZv4erkHrAkxpUwTIMpUIM85UTc9oOtceryjZIKttIwbMMl5PYiO3gPFp8QbU5xIZNOLKHQbY0hEvGGJnuXeLljaD1wgHXSl19DrAno6RV0/4Stouxtiz2KAIFoU3DRSxJcNy/BNAw5uq44hEnOpI6erfRidB0SXLOoref5zdul51/wPEE9+Bqs8TmhV/2YUjPdK74GOqWbsiJHuVAU23JDvf41nq8ogrlmwNWCMGocp756taZxSKjtMBjf+fVTaF7YGO9V1ufIJSQ46SC9UbJ7k7uXeCG1Z116zXQzgSY0ZxY9b46VxngItlPdOp6lPJGNzrwx5w/l8/Nr9GzS98yL1rT3pMFTt3CqNUNhCGyQQKLUkNWzeeI6plb5OAkec6xhzwOKbKTZ+lmK9H4al5YI/CU9ltelgNHxaEievm+3fw6JGzGS0gDY9jJYOXBGX69xecNZYFIYTNdUYDOnsnTivHl66zatHNjxQE9PQpNM5D6PhGz9eplAc7fIA3mGDrwnaGOgcpCUUr98xuQtnJC9X2AZNIo2/yY6d4QIcQs="
