language : java
jdk:
#  - openjdk8
 # - openjdk11
  #- openjdk13
before_install:
    - chmod +x src/test/java/com/example/helloworld/
jobs:
  include:
  
    - stage: IntegrationTest
      script: ./src/test/resources/test-example.yml
      script: ./src/test/java/com/example/helloworld/IntegrationTest.java
      

    - stage: deploy
      script: ./deploy
