language : java
jobs:
  include:
    - stage: test
      script: src/test/java/com/example/helloworld/IntegrationTest.java
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy
